### PR TITLE
mongoose validation error bugfix

### PR DESCRIPTION
**Pull request by CallForSanity**
This fixes a mongoose validation error.

### CODE REVIEW

**Comment by marcelklehr** [comment]
Thank you!

**Comment by CallForSanity** [comment]
You are welcome!

We really like your work and are actually
thinking about writing a tutorial that describes how to
combine gulf, websockets and the quilljs editor.

We already did this in our project:
https://github.com/openevocracy/openevocracy

Cheers,
Patrick

2016-06-30 15:43 GMT+02:00 Marcel Klehr notifications@github.com:

**Comment by marcelklehr** [comment]
Ah, that would be cool! Interesting stuff. I found liquid democracy quite compelling. Is this the successor? I see you've been toying with etherpad. Have you checked out hive.js? It has Gulf is at its core, too.

**Comment by CallForSanity** [comment]
Hi,

yes, unfortunately there are still some traces of etherpad left,
as we are currently in the process of replacing it.

We considered hivejs too, but did not like the fact that,
like etherpad, it is designed as a monolithic standalone app
(at least from what we understood).
We wanted everything under control in our app,
like right now with gulf, gulf-mongodb, socketjs and quilljs.
The reason for that is we need a tighter
integration due to some planned features.
Hivejs does not seem very "embedding"-friendly, but I might be wrong.

As to the project itself. It is going to be a new approach to democracy,
with more focus on consensus. Essentially this means we will have
multiple groups of five people working on proposals, thus gulf and quill,
see http://openevocracy.org/ .
We believe that current representative democracy mostly does not
actually represent the people, while direct democracy has problems
due to misinformed/populist choices. We try to find a middle ground here.
I don't know if we are "succeeding" liquid democracy,
but we are trying something new :)

We are fairly new to the nodejs ecosystem, thus many things might look
strange.
For example we are still using requirejs, although everybody seems to have
moved to actual build systems or reactjs ;)

Anyways, thank you for your help!
Patrick

2016-06-30 20:34 GMT+02:00 Marcel Klehr notifications@github.com:

**Comment by marcelklehr** [comment]
Hi Patrick,

re standalone-ness: Yeah, hive.js is a bit like etherpad in that regard, which is not sitting well with me as well... The web platform currently only offers iframes for integrating apps, afaik, which is not very neat :/ That's one of the reasons why I created gulf, though, so people can choose the level of abstraction they need :)

re evocracy: sounds interesting. I wonder what happens if people are not motivated or not educated/knowledgeable for the subject in question, though. I do recognize the need for new approaches to democracy, though. Good luck with yours!

re js stack: I think that's a matter of taste, really. Backbone/Marionette and require.js are useful tools. As is react and browserify. Personally, I found Backbone a little too restrictive/opinionated, forcing me to come up with solutions I didn't have without it. What I like about redux (which I'm using in hive.js), is the pure-functional nature and the flexibility. Of course the cost of that flexibility is that I have to implement basic functionality, like syncing models with the server, myself (Might not be too bad a thing, though. I'm not sure.)

Cheers,
Marcel

**Comment by marcelklehr** [comment]
Hey again,

I've been thinking about your insight on the usability of hive.js for plugging it into a host app, and I think you're right. Having all client-side functionality crammed into one client-side stack that is hard to change and only possible to plug into other apps as an iframe is very limiting. I think I found a solution, though. If you want we could chat about it on https://gitter.im/hivejs/chat (I think the conversation has outgrown this space anyhow ;) )

Cheers!

**Pull request merged**
